### ISSUE TITLE
empty data

### ISSUE THREAD

**Issue by zinzui12345** [gadingnst/hadith-api#5]
Ahmad's hadith is only available up to 12.
![image](https://user-images.githubusercontent.com/48501018/222293280-ef663d8f-89f6-4116-8264-df73529b0d74.png)

**Comment by gadingnst** [comment]
because the number of hadith that you requested is not available in the data. it skips to the number 14 and 78.

but @0xWerz already fixed the response at #7 

![Screenshot 2023-07-11 at 00 30 49](https://github.com/gadingnst/hadith-api/assets/38345393/284bd882-4f4e-4118-94c3-c36fef77cde1)
